version: "3"

services:
    api:
      build: .
      depends_on: 
        - postgres
      ports: 
        - 8000:8000
      volumes:
        - ./:/usr/src/app:ro
      # env_file:
      #   - ./
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      environment:
        - DATABASE_HOSTNAME=postgres
        - DATABASE_PORT=5432
        - DATABASE_PASSWORD=1994
        - DATABASE_NAME=fastapi
        - DATABASE_USERNAME=postgres
        - SECRET_KEY=wadwadiwa897d90a8wyd0wa8fhd89eqayudfwa
        - ALGORITHM=HS256
        - ACCESS_TOKEN_EXPIRE_MINUTES=30
    postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=1994
        - POSTGRES_DB=fastapi

      volumes: 
        - postgres-db:/var/lib/postgresql/data
    
volumes: 
  postgres-db: 
    

# bind mount, volumes
# docker build -t <name> .
# docker run <name>
# docker-compose build 
# docker-compose up -d 
# docker-compose down